=== npalexey/JavaBeansInitializer/src/main/resources/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="beans" type="beansType"/>
  <xs:complexType name="beansType">
    <xs:sequence>
      <xs:element type="importType" name="import" maxOccurs="unbounded" minOccurs="0">
        <xs:annotation>
          <xs:documentation>optional</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="beanType" name="bean" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="mainType" name="main">
        <xs:annotation>
          <xs:documentation>required, but should be only one</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="importType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="src" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="beanType">
    <xs:sequence>
      <xs:element type="propertyType" name="property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
    <xs:attribute type="xs:string" name="class" use="optional"/>
  </xs:complexType>
  <xs:complexType name="mainType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bean"/>
        <xs:attribute type="xs:string" name="method"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="propertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== npalexey/JavaBeansInitializer/src/main/resources/beansPerson.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="beans.xsd">
    <!-- optional -->
    <import src="src/main/resources/beans-resources.xml"/>
    <!--<import src="classpath:/common/service-beans.xml"/>-->
    <bean id="executor" class="com.nikitiuk.javabeansinitializer.beans.Person" >
        <property name="name" value="Executor" />
        <property name="cityOfResidence" value="Odessa" />
        <property name="boss" ref="eBoss" />
        <property name="job" value="ExecutorOfThings" />
    </bean>

    <bean id="eBoss" class="com.nikitiuk.javabeansinitializer.beans.Person" >
        <property name="name" value="EBoss" />
        <property name="cityOfResidence" value="Kyiv" />
        <property name="salary" value="2415" />
        <property name="wealthy" value="true" />
        <property name="job" value="Bossing The Executor" />
    </bean>

    <!-- required, but should be only one -->
    <main bean="executor" method="init" />
</beans>
